# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 118898f847edfc27e4908f4cc212cebb47c3ce6585cd01b807ab57b12ba7212a2900032ece30ce93b67acc7998b61f5e98b329ae8f6edee20175367c48ad6e76

test:
  secret_key_base: bb2632841282d44732c598493410a7db82cc761f7666133bdc3f7dcea1f1cc484f9f2dd6499b4fc698c2db898ec87812eb15464c76974a1ed58e5c7272f6ecad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
